/* DELETE 'stravadb' database*/
DROP SCHEMA IF EXISTS stravadb;
/* DELETE USER 'sd' AT LOCAL SERVER*/
DROP USER IF EXISTS 'sd'@'%';

/* CREATE ''stravadb' DATABASE */
CREATE SCHEMA stravadb;
/* CREATE THE USER 'sd' AT LOCAL SERVER WITH PASSWORD 'sd' */
CREATE USER IF NOT EXISTS 'sd'@'%' IDENTIFIED BY 'sd';
/* GRANT FULL ACCESS TO THE DATABASE FOR THE USER 'sd' AT LOCAL SERVER*/
GRANT ALL ON stravadb.* TO 'sd'@'%';
